[package]
name = "trading-sdk"
version = "0.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
tokio = { version = "*", features = ["full"] }
uuid = { version = "*", features = ["v4"] }
num_enum = "*"